# 🏆 Đánh Giá Toàn Diện Hệ Thống Traffic RAG

Notebook này đánh giá **Traffic RAG** theo trình tự từng bước, từ đơn giản (Gemini thuần) đến phức tạp (Agentic RAG).

### Các metrics được đo:
| Metric | Ý nghĩa | Công cụ |
|--------|----------|---------|
| **Cosine Similarity** | Độ tương đồng ngữ nghĩa giữa câu trả lời và ground truth | Gemini Embedding |
| **ROUGE-L** | Độ trùng khớp chuỗi con chung dài nhất | rouge_score |
| **F1 Token** | Overlap từ ngữ giữa answer và ground truth | Manual |
| **Precision@5** | Tỷ lệ kết quả retrieval đúng trong top-5 | EvaluationManager |
| **Faithfulness (Ragas)** | Câu trả lời có dựa vào context không? | Ragas |
| **Answer Relevancy (Ragas)** | Câu trả lời có trả lời đúng câu hỏi không? | Ragas |
| **Latency** | Thời gian xử lý mỗi câu hỏi (giây) | time |

### Các phương pháp được so sánh:
- **Gemini Thuần** (không RAG)
- **Naive RAG** (Hybrid Search + Gemini)
- **Agentic RAG** (Query Rewrite + Hybrid Search + Gemini)

## 0. Setup & Import

In [1]:
import sys, os, json, time

# ==== CẤU HÌNH ĐƯỜNG DẪN GỐC ====
# Thay đổi TRAFFIC_RAG_ROOT nếu chạy trên máy khác
TRAFFIC_RAG_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
print(f"Project root: {TRAFFIC_RAG_ROOT}")

if TRAFFIC_RAG_ROOT not in sys.path:
    sys.path.insert(0, TRAFFIC_RAG_ROOT)

import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics.pairwise import cosine_similarity
from rouge_score import rouge_scorer
import google.generativeai as genai
from dotenv import load_dotenv

# Load env
load_dotenv(os.path.join(TRAFFIC_RAG_ROOT, '.env'))

# Import các module của traffic_rag
from source.core.config import Settings
from source.generation.rag_pipeline import TrafficRAGPipeline
from source.evaluation.eval_manager import EvaluationManager

settings = Settings()
API_KEY = settings.api_key or os.getenv('API_KEY')
genai.configure(api_key=API_KEY)

print('✅ Import thành công!')

Project root: /media/pphong/D:/Do_An_Tot_Nghiep/GitHub1/traffic_rag

/home/pphong/venv/LLM_Agentic/lib/python3.10/site-packages/google/api_core/_python_version_support.py:273: FutureWarning: You are using a Python version (3.10.12) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
/home/pphong/venv/LLM_Agentic/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_57562/2749242904.py:16: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

✅ Import thành công!

## 1. Khởi Tạo Pipeline và Tải Dữ Liệu Ground Truth

In [4]:
# ------ Khởi tạo pipeline ------
print('Đang khởi tạo RAG Pipeline (có thể mất 1-2 phút để tải embedding model)...')
pipeline = TrafficRAGPipeline(settings)
eval_mgr = EvaluationManager()
print('✅ Pipeline sẵn sàng!')

Đang khởi tạo RAG Pipeline (có thể mất 1-2 phút để tải embedding model)...
 Đang tải mô hình nhúng: KeepItReal/vietnamese-sbert...

/media/pphong/D:/Do_An_Tot_Nghiep/GitHub1/traffic_rag/source/retrieval/hybrid_retriever.py:14: UserWarning: Qdrant client version 1.14.2 is incompatible with server version 1.17.0. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  self.client = QdrantClient(host=self.settings.qdrant_host, port=self.settings.qdrant_port)
/media/pphong/D:/Do_An_Tot_Nghiep/GitHub1/traffic_rag/source/model/embedding_model.py:15: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  self.embeddings_bkai = HuggingFaceEmbeddings(

Đã khởi tạo Embedding Model thành công!
✅ Pipeline sẵn sàng!

In [5]:
# ------ Tải Ground Truth ------
GT_PATH = os.path.join(TRAFFIC_RAG_ROOT, 'source_research', 'Eval_System', 'dataset', 'ground_truth_traffic.csv')
df_gt = pd.read_csv(GT_PATH)
print(f'✅ Loaded {len(df_gt)} câu hỏi ground truth')
print(f'Các cột: {df_gt.columns.tolist()}')
df_gt.head()

✅ Loaded 25 câu hỏi ground truth
Các cột: ['question', 'expected_answer', 'expected_article', 'category']

,question,expected_answer,expected_article,category
0,"Người điều khiển xe máy có nồng độ cồn vượt 0,...",Phạt tiền từ 6.000.000 đến 8.000.000 đồng,Điều 6,Nong_Do_Con
1,Xe máy vượt tốc độ quy định từ 10km/h đến dưới...,Phạt tiền từ 800.000 đồng đến 1.000.000 đồng,Điều 6,Toc_Do
2,Ô tô vượt đèn đỏ tại ngã tư bị phạt thế nào?,Phạt tiền từ 4.000.000 đến 6.000.000 đồng,Điều 5,Den_Tin_Hieu
3,Không đội mũ bảo hiểm khi đi xe máy phạt bao n...,Phạt tiền từ 400.000 đồng đến 600.000 đồng,Điều 11,Mu_Bao_Hiem
4,Xe ô tô không có bảo hiểm trách nhiệm dân sự b...,Phạt tiền từ 1.000.000 đến 2.000.000 đồng,Điều 21,Bao_Hiem

## 2. Định Nghĩa Các Hàm Tính Metrics

In [6]:
# ==== ROUGE-L ====
rouge_scorerer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)

def compute_rouge_l(pred: str, ref: str) -> float:
    """Tính ROUGE-L giữa câu trả lời và ground truth."""
    try:
        score = rouge_scorerer.score(str(ref), str(pred))
        return round(score['rougeL'].fmeasure, 4)
    except:
        return 0.0

# ==== F1 Token Score ====
def compute_f1_token(pred: str, ref: str) -> float:
    """Tính F1 dựa trên overlap từ ngữ (tokenized)."""
    pred_tokens = str(pred).lower().split()
    ref_tokens = str(ref).lower().split()
    common = set(pred_tokens) & set(ref_tokens)
    if not pred_tokens or not ref_tokens:
        return 0.0
    precision = len(common) / len(pred_tokens)
    recall = len(common) / len(ref_tokens)
    if precision + recall == 0:
        return 0.0
    return round(2 * precision * recall / (precision + recall), 4)

# ==== Cosine Similarity (Gemini Embedding) ====
def get_gemini_embedding(text: str) -> list:
    """Nhúng văn bản bằng Gemini gemini-embedding-001."""
    try:
        result = genai.embed_content(
            model='models/gemini-embedding-001',
            content=str(text),
            task_type='SEMANTIC_SIMILARITY'
        )
        return result['embedding']
    except Exception as e:
        print(f'  ⚠️ Embedding error: {e}')
        return [0.0] * 768

def compute_cosine(emb1: list, emb2: list) -> float:
    """Tính cosine similarity giữa 2 vector embedding."""
    sim = cosine_similarity([emb1], [emb2])[0][0]
    return round(float(sim), 4)

print('✅ Đã định nghĩa xong các hàm tính metrics!')
print('  - compute_rouge_l(pred, ref)')
print('  - compute_f1_token(pred, ref)')
print('  - get_gemini_embedding(text)')
print('  - compute_cosine(emb1, emb2)')

✅ Đã định nghĩa xong các hàm tính metrics!
  - compute_rouge_l(pred, ref)
  - compute_f1_token(pred, ref)
  - get_gemini_embedding(text)
  - compute_cosine(emb1, emb2)

## 3. Thu Thập Câu Trả Lời Từ Các Hệ Thống

> ⚠️ **Lưu ý**: Mỗi cell bên dưới gọi API Gemini. Chạy từng cell và lưu checkpoint định kỳ để tránh mất dữ liệu khi bị rate limit.

In [7]:
# === Đường dẫn file kết quả (checkpoint) ===
RESULTS_PATH = os.path.join(TRAFFIC_RAG_ROOT, 'source_research', 'Eval_System', 'dataset', 'eval_responses.csv')

# Nếu đã có file, load lại để chạy tiếp
if os.path.exists(RESULTS_PATH):
    df_results = pd.read_csv(RESULTS_PATH)
    print(f'📂 Tải file checkpoint ({len(df_results)} dòng): {RESULTS_PATH}')
else:
    df_results = df_gt.copy()
    print(f'🆕 Tạo mới file kết quả với {len(df_results)} câu hỏi')

# Đảm bảo các cột kết quả tồn tại
for col in ['answer_gemini_pure', 'answer_rag', 'contexts_rag', 'precision_at_5', 'latency']:
    if col not in df_results.columns:
        df_results[col] = None

df_results.head()

📂 Tải file checkpoint (25 dòng): /media/pphong/D:/Do_An_Tot_Nghiep/GitHub1/traffic_rag/source_research/Eval_System/dataset/eval_responses.csv

,question,expected_answer,expected_article,category,answer_gemini_pure,answer_rag,contexts_rag,precision_at_5,latency,answer_naive_rag
0,"Người điều khiển xe máy có nồng độ cồn vượt 0,...",Phạt tiền từ 6.000.000 đến 8.000.000 đồng,Điều 6,Nong_Do_Con,Trả lời: Theo Nghị định 100/2019/NĐ-CP (được s...,"Chào bạn, với tư cách là Luật sư chuyên về Gia...",c) Điều khiển xe trên đường mà trong máu hoặc ...,1.0,7.45,"Dựa trên tài liệu bạn cung cấp, nội dung này q..."
1,Xe máy vượt tốc độ quy định từ 10km/h đến dưới...,Phạt tiền từ 800.000 đồng đến 1.000.000 đồng,Điều 6,Toc_Do,Theo điểm c khoản 3 Điều 6 Nghị định 100/2019/...,"Chào bạn, với tư cách là Luật sư chuyên về Gia...",a) Điều khiển xe chạy quá tốc độ quy định từ 0...,1.0,7.18,"Trả lời: Theo Nghị định 100/2019/NĐ-CP, hành v..."
2,Ô tô vượt đèn đỏ tại ngã tư bị phạt thế nào?,Phạt tiền từ 4.000.000 đến 6.000.000 đồng,Điều 5,Den_Tin_Hieu,Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Ngh...,"Chào bạn, với tư cách là Luật sư chuyên về Gia...",8. Phạt tiền từ 3.000.000 đồng đến 5.000.000 đ...,1.0,8.51,"Chào bạn, với tư cách là chuyên gia Luật Giao ..."
3,Không đội mũ bảo hiểm khi đi xe máy phạt bao n...,Phạt tiền từ 400.000 đồng đến 600.000 đồng,Điều 11,Mu_Bao_Hiem,"Theo Nghị định 100/2019/NĐ-CP (được sửa đổi, b...","Chào bạn, với tư cách là Luật sư chuyên về Gia...","b) Không đội “mũ bảo hiểm cho người đi mô tô, ...",0.0,18.65,Trả lời: Theo quy định tại Nghị định 100/2019/...
4,Xe ô tô không có bảo hiểm trách nhiệm dân sự b...,Phạt tiền từ 1.000.000 đến 2.000.000 đồng,Điều 21,Bao_Hiem,Theo quy định tại **Điểm b Khoản 4 Điều 21 Ngh...,"Chào bạn, với tư cách là Luật sư chuyên về Gia...",d) Chứng nhận kiểm định an toàn kỹ thuật và bả...,0.0,8.15,Trả lời: Theo quy định tại Điều 21 Nghị định 1...

In [ ]:
# ==== 3.1: Gemini Thuần (không RAG) ====
gemini_model = genai.GenerativeModel('gemini-3.1-flash-lite-preview')

import re as _re

def get_gemini_pure_answer(question: str, max_retries: int = 5) -> str:
    """Gọi Gemini trực tiếp không có context, tự chờ nếu bị rate limit."""
    prompt = f"""Bạn là chuyên gia Luật Giao thông đường bộ Việt Nam.
Hãy trả lời câu hỏi sau một cách ngắn gọn, chính xác.

Câu hỏi: {question}
Trả lời:"""
    for attempt in range(max_retries):
        try:
            response = gemini_model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            err = str(e)
            if '429' in err:
                # Lấy thời gian retry từ thông báo lỗi
                match = _re.search(r'retry in (\d+)', err)
                wait = int(match.group(1)) + 5 if match else 65
                print(f'   Rate limit. Chờ {wait}s (lần {attempt+1}/{max_retries})...')
                time.sleep(wait)
            else:
                print(f'  ❌ Error: {e}')
                return ''
    print('  ❌ Hết số lần retry.')
    return ''

print('🚀 Bắt đầu thu thập câu trả lời Gemini Thuần...')
for idx, row in tqdm(df_results.iterrows(), total=len(df_results), desc='Gemini Pure'):
    if pd.notna(df_results.at[idx, 'answer_gemini_pure']) and str(df_results.at[idx, 'answer_gemini_pure']).strip() != '':
        continue  # Bỏ qua nếu đã có
    df_results.at[idx, 'answer_gemini_pure'] = get_gemini_pure_answer(row['question'])
    time.sleep(4)  # Tránh rate limit

df_results.to_csv(RESULTS_PATH, index=False)
print(f'✅ Đã lưu checkpoint → {RESULTS_PATH}')

In [ ]:
# ==== 3.2: RAG Thuần Cơ Bản (Naive RAG - BM25 search + Gemini) ====
# Không dùng query rewrite, không hybrid, chỉ BM25 đơn giản

import re as _re

def get_naive_rag_answer(question: str, max_retries: int = 5) -> str:
    """RAG đơn giản: BM25 search thẳng câu hỏi → Gemini trả lời dựa vào context."""
    # 1. Tìm kiếm BM25 đơn giản (không rewrite)
    try:
        results = pipeline.retriever.search(question, top_k=5)
    except Exception as e:
        print(f"  ❌ Retrieval error: {e}")
        return ''

    # 2. Tạo context
    context_str = ""
    for i, res in enumerate(results[:5]):
        chunk = res['chunk']
        m = chunk['metadata']
        context_str += f"[{i+1}] {m.get('ten_van_ban', 'Luật')} | {m.get('dieu', '?')}\nNội dung: {chunk['content']}\n\n"

    # 3. Gọi Gemini với context
    prompt = f"""Bạn là chuyên gia Luật Giao thông đường bộ Việt Nam.
Dựa vào các tài liệu pháp luật dưới đây, hãy trả lời câu hỏi một cách ngắn gọn, chính xác.

TÀI LIỆU:
{context_str}

Câu hỏi: {question}
Trả lời:"""

    for attempt in range(max_retries):
        try:
            response = gemini_model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            if '429' in str(e):
                match = _re.search(r'retry in (\d+)', str(e))
                wait = int(match.group(1)) + 5 if match else 65
                print(f'  ⏳ Rate limit. Chờ {wait}s (lần {attempt+1}/{max_retries})...')
                time.sleep(wait)
            else:
                print(f'  ❌ Error: {e}')
                return ''
    return ''

# Thêm cột cho Naive RAG nếu chưa có
if 'answer_naive_rag' not in df_results.columns:
    df_results['answer_naive_rag'] = None

print('🚀 Bắt đầu thu thập câu trả lời RAG Thuần Cơ Bản...')
for idx, row in tqdm(df_results.iterrows(), total=len(df_results), desc='Naive RAG'):
    if pd.notna(df_results.at[idx, 'answer_naive_rag']) and str(df_results.at[idx, 'answer_naive_rag']).strip() != '':
        continue  # Bỏ qua nếu đã có
    df_results.at[idx, 'answer_naive_rag'] = get_naive_rag_answer(row['question'])
    df_results.to_csv(RESULTS_PATH, index=False)
    time.sleep(4)  # Tránh rate limit

print(f'✅ Hoàn thành RAG Thuần! Đã lưu → {RESULTS_PATH}')

In [ ]:
# ==== 3.2: Agentic RAG (Query Rewrite + Hybrid Search + Gemini) ====
import re as _re

print('🚀 Bắt đầu thu thập câu trả lời RAG...')
for idx, row in tqdm(df_results.iterrows(), total=len(df_results), desc='Agentic RAG'):
    if pd.notna(df_results.at[idx, 'answer_rag']) and str(df_results.at[idx, 'answer_rag']).strip() != '':
        continue  # Bỏ qua nếu đã có

    start_time = time.time()
    success = False
    for attempt in range(5):
        try:
            result = pipeline.run(row['question'])
            latency = round(time.time() - start_time, 2)

            df_results.at[idx, 'answer_rag'] = result['answer']
            df_results.at[idx, 'latency'] = latency

            # Precision@5
            p_at_5 = eval_mgr.calculate_precision_at_k(
                result['references'],
                row.get('expected_article', ''),
                k=5
            )
            df_results.at[idx, 'precision_at_5'] = p_at_5

            # Contexts
            contexts = [ref['chunk']['content'][:200] for ref in result['references'][:3]]
            df_results.at[idx, 'contexts_rag'] = ' | '.join(contexts)
            success = True
            break
        except Exception as e:
            if '429' in str(e):
                match = _re.search(r'retry in (\d+)', str(e))
                wait = int(match.group(1)) + 5 if match else 65
                print(f'  ⏳ Rate limit. Chờ {wait}s (lần {attempt+1}/5)...')
                time.sleep(wait)
            else:
                print(f'\n❌ Lỗi tại [{idx}] {row["question"][:50]}: {e}')
                df_results.at[idx, 'answer_rag'] = ''
                break

    # Lưu checkpoint sau mỗi câu
    df_results.to_csv(RESULTS_PATH, index=False)
    time.sleep(3)

print(f'✅ Hoàn thành! Đã lưu → {RESULTS_PATH}')

## 4. Tính Toán Các Metrics Đánh Giá

In [8]:
# Load lại file kết quả đầy đủ
df_results = pd.read_csv(RESULTS_PATH)

# Lọc các dòng có đủ dữ liệu để đánh giá
df_eval = df_results.dropna(subset=['expected_answer', 'answer_rag', 'answer_gemini_pure']).copy()
df_eval = df_eval[df_eval['answer_rag'] != ''].copy()
df_eval = df_eval[df_eval['answer_gemini_pure'] != ''].copy()
df_eval = df_eval.reset_index(drop=True)

print(f'📊 Số câu hỏi để đánh giá: {len(df_eval)}')

📊 Số câu hỏi để đánh giá: 25

In [9]:
# ==== 4.1: Tính ROUGE-L và F1 Token ====
print('⏳ Tính ROUGE-L và F1 Token...')

# Cho Gemini Thuần
df_eval['rouge_l_pure'] = df_eval.apply(
    lambda row: compute_rouge_l(row['answer_gemini_pure'], row['expected_answer']), axis=1
)
df_eval['f1_pure'] = df_eval.apply(
    lambda row: compute_f1_token(row['answer_gemini_pure'], row['expected_answer']), axis=1
)

# Cho RAG
df_eval['rouge_l_rag'] = df_eval.apply(
    lambda row: compute_rouge_l(row['answer_rag'], row['expected_answer']), axis=1
)
df_eval['f1_rag'] = df_eval.apply(
    lambda row: compute_f1_token(row['answer_rag'], row['expected_answer']), axis=1
)

print('✅ Xong ROUGE-L và F1!')

⏳ Tính ROUGE-L và F1 Token...
✅ Xong ROUGE-L và F1!

In [10]:
# ==== 4.2: Tính Cosine Similarity (Gemini Embedding) ====
# ⚠️ Cell này gọi Gemini Embedding API, tốn thời gian và quota
# Mỗi câu hỏi cần 3 lần embed (ground_truth, gemini_pure, rag)

print('⏳ Đang tính Cosine Similarity (Gemini Embedding)...')
print(f'   Sẽ gọi API khoảng {len(df_eval)*3} lần')

gt_embeddings = []
pure_embeddings = []
rag_embeddings = []

for idx, row in tqdm(df_eval.iterrows(), total=len(df_eval), desc='Embedding'):
    gt_embeddings.append(get_gemini_embedding(row['expected_answer']))
    pure_embeddings.append(get_gemini_embedding(row['answer_gemini_pure']))
    rag_embeddings.append(get_gemini_embedding(row['answer_rag']))
    time.sleep(1)  # Tránh rate limit

df_eval['cosine_pure'] = [compute_cosine(p, g) for p, g in zip(pure_embeddings, gt_embeddings)]
df_eval['cosine_rag'] = [compute_cosine(r, g) for r, g in zip(rag_embeddings, gt_embeddings)]

# Lưu lại kết quả
df_eval.to_csv(RESULTS_PATH.replace('.csv', '_with_metrics.csv'), index=False)
print('✅ Đã tính xong Cosine Similarity và lưu file!')

⏳ Đang tính Cosine Similarity (Gemini Embedding)...
   Sẽ gọi API khoảng 75 lần

Embedding:   0%|          | 0/25 [00:00<?, ?it/s]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:   4%|▍         | 1/25 [00:01<00:39,  1.63s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:   8%|▊         | 2/25 [00:02<00:32,  1.41s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  12%|█▏        | 3/25 [00:04<00:29,  1.35s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  16%|█▌        | 4/25 [00:05<00:27,  1.32s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  20%|██        | 5/25 [00:06<00:25,  1.29s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  24%|██▍       | 6/25 [00:07<00:24,  1.29s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  28%|██▊       | 7/25 [00:09<00:22,  1.28s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  32%|███▏      | 8/25 [00:10<00:21,  1.27s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  36%|███▌      | 9/25 [00:11<00:20,  1.26s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  40%|████      | 10/25 [00:12<00:18,  1.26s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  44%|████▍     | 11/25 [00:14<00:17,  1.25s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  48%|████▊     | 12/25 [00:15<00:16,  1.25s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  52%|█████▏    | 13/25 [00:16<00:15,  1.25s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  56%|█████▌    | 14/25 [00:17<00:13,  1.24s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  60%|██████    | 15/25 [00:19<00:12,  1.24s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  64%|██████▍   | 16/25 [00:20<00:12,  1.39s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  68%|██████▊   | 17/25 [00:22<00:10,  1.37s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  72%|███████▏  | 18/25 [00:23<00:09,  1.34s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  76%|███████▌  | 19/25 [00:24<00:07,  1.32s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  80%|████████  | 20/25 [00:25<00:06,  1.30s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  84%|████████▍ | 21/25 [00:27<00:05,  1.27s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  88%|████████▊ | 22/25 [00:28<00:03,  1.26s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  92%|█████████▏| 23/25 [00:29<00:02,  1.25s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding:  96%|█████████▌| 24/25 [00:30<00:01,  1.24s/it]

  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.
  ⚠️ Embedding error: 404 models/text-embedding-004 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.

Embedding: 100%|██████████| 25/25 [00:32<00:00,  1.28s/it]

✅ Đã tính xong Cosine Similarity và lưu file!

## 5. Tổng Hợp Kết Quả và Hiển Thị Bảng So Sánh

In [18]:
# ==== BẢNG SO SÁNH TỔNG QUAN ====
print('=' * 65)
print('📊 BẢNG SO SÁNH HIỆU SUẤT CÁC PHƯƠNG PHÁP RAG')
print('=' * 65)

summary = {
    'Phương pháp': ['Gemini Thuần (no RAG)', 'RAG Thuần Cơ Bản', 'Agentic RAG (traffic_rag)'],
    'Cosine Similarity': [
        round(df_eval['cosine_pure'].mean(), 4),
        round(df_eval.get('cosine_naive', df_eval['cosine_pure']).mean(), 4),
        round(df_eval['cosine_rag'].mean(), 4)
    ],
    'ROUGE-L': [
        round(df_eval['rouge_l_pure'].mean(), 4),
        round(df_eval.get('rouge_l_naive', df_eval['rouge_l_pure']).mean(), 4),
        round(df_eval['rouge_l_rag'].mean(), 4)
    ],
    'F1 Token': [
        round(df_eval['f1_pure'].mean(), 4),
        round(df_eval.get('f1_naive', df_eval['f1_pure']).mean(), 4),
        round(df_eval['f1_rag'].mean(), 4)
    ],
    'Precision@5': [
        '-',
        '-',
        round(df_eval['precision_at_5'].mean(), 4)
    ],
    'Latency (s)': [
        '-',
        '-',
        round(df_eval['latency'].mean(), 2)
    ]
}

df_summary = pd.DataFrame(summary)
df_summary = df_summary.set_index('Phương pháp')

print(df_summary.to_string())
print('=' * 65)

=================================================================
📊 BẢNG SO SÁNH HIỆU SUẤT CÁC PHƯƠNG PHÁP RAG
=================================================================
                           Cosine Similarity  ROUGE-L  F1 Token Precision@5 Latency (s)
Phương pháp
Gemini Thuần (no RAG)                    0.0   0.2006    0.1518           -           -
RAG Thuần Cơ Bản                         0.0   0.2006    0.1518           -           -
Agentic RAG (traffic_rag)                0.0   0.0407    0.0280        0.56        13.0
=================================================================

In [19]:
# ==== BẢNG KẾT QUẢ CHI TIẾT THEO DANH MỤC ====
print('\n📂 KẾT QUẢ THEO DANH MỤC (category):')
if 'category' in df_eval.columns:
    df_by_cat = df_eval.groupby('category').agg(
        Cosine_RAG=('cosine_rag', 'mean'),
        ROUGE_L_RAG=('rouge_l_rag', 'mean'),
        F1_RAG=('f1_rag', 'mean'),
        Precision_at_5=('precision_at_5', 'mean'),
        Count=('question', 'count')
    ).round(4)
    print(df_by_cat.to_string())
else:
    print('  (Không có cột category trong dữ liệu)')

📂 KẾT QUẢ THEO DANH MỤC (category):
                Cosine_RAG  ROUGE_L_RAG  F1_RAG  Precision_at_5  Count
category
Bao_Hiem               0.0       0.0202  0.0159          0.0000      1
Bien_Bao               0.0       0.0439  0.0279          0.0000      1
Chieu_Duong            0.0       0.0377  0.0239          1.0000      1
Chở_Người              0.0       0.0253  0.0165          0.0000      1
Day_An_Toan            0.0       0.0979  0.0765          1.0000      1
Den_Chieu_Sang         0.0       0.0320  0.0310          0.0000      1
Den_Tin_Hieu           0.0       0.0310  0.0187          1.0000      2
Dien_Thoai             0.0       0.0311  0.0177          1.0000      1
Dung_Do                0.0       0.0322  0.0122          0.0000      1
Duong_Cao_Toc          0.0       0.0412  0.0320          1.0000      1
GPLX                   0.0       0.0278  0.0140          1.0000      2
Mu_Bao_Hiem            0.0       0.0479  0.0372          0.5000      2
Nguoi_Di_Bo            0.0       0.0511  0.0312          1.0000      1
Nong_Do_Con            0.0       0.0582  0.0403          0.3333      3
Tai_Trong              0.0       0.0528  0.0371          1.0000      1
Thiet_Bi               0.0       0.0415  0.0412          0.0000      1
Toc_Do                 0.0       0.0318  0.0196          0.5000      2
Via_He                 0.0       0.0286  0.0113          0.0000      1
Vuot_Xe                0.0       0.0299  0.0255          1.0000      1

In [20]:
# ==== CHI TIẾT TỪNG CÂU HỎI ====
print('\n📝 KẾT QUẢ CHI TIẾT TỪNG CÂU HỎI:')

for idx, row in df_eval.iterrows():
    print(f"\n{'─'*60}")
    print(f"[{idx+1}] ❓ {row['question']}")
    print(f"✅ Ground Truth : {row['expected_answer'][:100]}")
    print(f"🤖 Gemini Thuần: {str(row['answer_gemini_pure'])[:100]}")
    print(f"🔍 Agentic RAG : {str(row['answer_rag'])[:100]}")
    print(f"📊 Metrics     : Cosine_RAG={row.get('cosine_rag', '-')}, ROUGE-L_RAG={row.get('rouge_l_rag', '-')}, F1_RAG={row.get('f1_rag', '-')}, P@5={row.get('precision_at_5', '-')}")
    print(f"⏱️ Latency     : {row.get('latency', '-')}s")

📝 KẾT QUẢ CHI TIẾT TỪNG CÂU HỎI:

────────────────────────────────────────────────────────────
[1] ❓ Người điều khiển xe máy có nồng độ cồn vượt 0,25mg/l khí thở bị phạt bao nhiêu tiền?
✅ Ground Truth : Phạt tiền từ 6.000.000 đến 8.000.000 đồng
🤖 Gemini Thuần: Trả lời: Theo Nghị định 100/2019/NĐ-CP (được sửa đổi bởi Nghị định 123/2021/NĐ-CP), người điều khiển
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn dự
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0443, F1_RAG=0.0283, P@5=1.0
⏱️ Latency     : 7.45s

────────────────────────────────────────────────────────────
[2] ❓ Xe máy vượt tốc độ quy định từ 10km/h đến dưới 20km/h bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 800.000 đồng đến 1.000.000 đồng
🤖 Gemini Thuần: Theo điểm c khoản 3 Điều 6 Nghị định 100/2019/NĐ-CP (được sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn dự
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0369, F1_RAG=0.0278, P@5=1.0
⏱️ Latency     : 7.18s

────────────────────────────────────────────────────────────
[3] ❓ Ô tô vượt đèn đỏ tại ngã tư bị phạt thế nào?
✅ Ground Truth : Phạt tiền từ 4.000.000 đến 6.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt đối với ô tô vượt đèn
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0394, F1_RAG=0.0272, P@5=1.0
⏱️ Latency     : 8.51s

────────────────────────────────────────────────────────────
[4] ❓ Không đội mũ bảo hiểm khi đi xe máy phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 400.000 đồng đến 600.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (được sửa đổi, bổ sung bởi Nghị định 123/2021/NĐ-CP), mức phạt đối với
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0232, F1_RAG=0.0088, P@5=0.0
⏱️ Latency     : 18.65s

────────────────────────────────────────────────────────────
[5] ❓ Xe ô tô không có bảo hiểm trách nhiệm dân sự bắt buộc bị phạt gì?
✅ Ground Truth : Phạt tiền từ 1.000.000 đến 2.000.000 đồng
🤖 Gemini Thuần: Theo quy định tại **Điểm b Khoản 4 Điều 21 Nghị định 100/2019/NĐ-CP** (sửa đổi, bổ sung bởi Nghị địn
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0202, F1_RAG=0.0159, P@5=0.0
⏱️ Latency     : 8.15s

────────────────────────────────────────────────────────────
[6] ❓ Người điều khiển xe máy không có giấy phép lái xe bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 1.000.000 đến 2.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi, bổ sung bởi Nghị định 123/2021/NĐ-CP), mức phạt đối với ngườ
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0286, F1_RAG=0.0163, P@5=1.0
⏱️ Latency     : 6.51s

────────────────────────────────────────────────────────────
[7] ❓ Xe máy dừng đỗ trên cầu có bị phạt không?
✅ Ground Truth : Phạt tiền từ 100.000 đến 200.000 đồng
🤖 Gemini Thuần: **Có.**

Theo điểm d khoản 3 Điều 6 Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP),
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0322, F1_RAG=0.0122, P@5=0.0
⏱️ Latency     : 5.49s

────────────────────────────────────────────────────────────
[8] ❓ Đi xe máy ban đêm không bật đèn chiếu sáng phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 100.000 đến 200.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt cụ thể như sau:

*
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn dự
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.032, F1_RAG=0.031, P@5=0.0
⏱️ Latency     : 7.54s

────────────────────────────────────────────────────────────
[9] ❓ Xe tải chạy quá tốc độ quy định trên 35km/h bị phạt thế nào?
✅ Ground Truth : Phạt tiền từ 10.000.000 đến 14.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt đối với người điều kh
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0266, F1_RAG=0.0115, P@5=0.0
⏱️ Latency     : 12.98s

────────────────────────────────────────────────────────────
[10] ❓ Điều khiển xe ô tô khi có nồng độ cồn trong máu vượt 80mg bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 30.000.000 đến 40.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt đối với người điều kh
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0525, F1_RAG=0.0377, P@5=0.0
⏱️ Latency     : 11.0s

────────────────────────────────────────────────────────────
[11] ❓ Xe máy chở quá 1 người phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 400.000 đến 600.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt cụ thể như sau:

1. *
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0253, F1_RAG=0.0165, P@5=0.0
⏱️ Latency     : 66.22s

────────────────────────────────────────────────────────────
[12] ❓ Ô tô đi vào đường cấm bị phạt gì?
✅ Ground Truth : Phạt tiền từ 3.000.000 đến 5.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (được sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức xử phạt ô tô đi vào đ
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0439, F1_RAG=0.0279, P@5=0.0
⏱️ Latency     : 23.82s

────────────────────────────────────────────────────────────
[13] ❓ Xe máy không có gương chiếu hậu bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 100.000 đến 200.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (được sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt cụ thể như sau:

🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0415, F1_RAG=0.0412, P@5=0.0
⏱️ Latency     : 40.01s

────────────────────────────────────────────────────────────
[14] ❓ Lái xe ô tô dùng điện thoại di động bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 1.000.000 đến 2.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt cụ thể như sau:

*
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0311, F1_RAG=0.0177, P@5=1.0
⏱️ Latency     : 10.7s

────────────────────────────────────────────────────────────
[15] ❓ Xe máy vượt đèn vàng bị xử phạt như thế nào?
✅ Ground Truth : Phạt tiền từ 400.000 đến 600.000 đồng
🤖 Gemini Thuần: Theo quy định tại **Nghị định 100/2019/NĐ-CP** (được sửa đổi bởi **Nghị định 123/2021/NĐ-CP**), hành
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0227, F1_RAG=0.0102, P@5=1.0
⏱️ Latency     : 6.92s

────────────────────────────────────────────────────────────
[16] ❓ Người điều khiển xe đạp không đội mũ bảo hiểm phạt bao nhiêu?
✅ Ground Truth : Người điều khiển xe đạp không bắt buộc đội mũ bảo hiểm theo Nghị định 100/123
🤖 Gemini Thuần: Theo quy định hiện hành, **không có quy định xử phạt vi phạm hành chính đối với người điều khiển xe
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0726, F1_RAG=0.0656, P@5=1.0
⏱️ Latency     : 11.12s

────────────────────────────────────────────────────────────
[17] ❓ Xe máy vượt ẩu nguy hiểm bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 1.000.000 đến 2.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt cho hành vi vượt xe s
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0299, F1_RAG=0.0255, P@5=1.0
⏱️ Latency     : 6.41s

────────────────────────────────────────────────────────────
[18] ❓ Ô tô chạy ngược chiều trên đường một chiều bị phạt gì?
✅ Ground Truth : Phạt tiền từ 10.000.000 đến 14.000.000 đồng
🤖 Gemini Thuần: Theo quy định tại **Nghị định 100/2019/NĐ-CP** (được sửa đổi, bổ sung bởi **Nghị định 123/2021/NĐ-CP
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0377, F1_RAG=0.0239, P@5=1.0
⏱️ Latency     : 6.73s

────────────────────────────────────────────────────────────
[19] ❓ Không có bằng lái xe ô tô bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 10.000.000 đến 14.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt tiền đối với người đi
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0271, F1_RAG=0.0118, P@5=1.0
⏱️ Latency     : 5.51s

────────────────────────────────────────────────────────────
[20] ❓ Xe máy đi vào đường cao tốc bị phạt gì?
✅ Ground Truth : Phạt tiền từ 1.000.000 đến 2.000.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (sửa đổi bởi Nghị định 123/2021/NĐ-CP), mức phạt đối với xe máy đi vào
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0412, F1_RAG=0.032, P@5=1.0
⏱️ Latency     : 8.2s

────────────────────────────────────────────────────────────
[21] ❓ Nồng độ cồn bằng 0 khi lái xe nghĩa là gì?
✅ Ground Truth : Người điều khiển xe không được sử dụng rượu bia với bất kỳ nồng độ nào khi điều khiển phương tiện
🤖 Gemini Thuần: Trả lời: Nồng độ cồn bằng 0 nghĩa là trong hơi thở và trong máu của người lái xe **không có nồng độ
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn dự
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0777, F1_RAG=0.055, P@5=0.0
⏱️ Latency     : 17.78s

────────────────────────────────────────────────────────────
[22] ❓ Xe tải vi phạm tải trọng bị phạt bao nhiêu?
✅ Ground Truth : Phạt tiền từ 3.000.000 đến 5.000.000 đồng tùy mức vượt tải
🤖 Gemini Thuần: Mức phạt tiền đối với hành vi chở hàng quá tải trọng cho phép của xe tải được quy định tại **Nghị đị
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0528, F1_RAG=0.0371, P@5=1.0
⏱️ Latency     : 6.34s

────────────────────────────────────────────────────────────
[23] ❓ Bắt buộc thắt dây an toàn khi ngồi ô tô không?
✅ Ground Truth : Có bắt buộc thắt dây an toàn khi ngồi ô tô. Không thắt bị phạt từ 400.000 đến 600.000 đồng
🤖 Gemini Thuần: Trả lời: **Có.**

Theo quy định tại **Luật Giao thông đường bộ 2008**, người ngồi ở các vị trí được
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0979, F1_RAG=0.0765, P@5=1.0
⏱️ Latency     : 9.33s

────────────────────────────────────────────────────────────
[24] ❓ Xe máy chạy lên vỉa hè bị phạt như thế nào?
✅ Ground Truth : Phạt tiền từ 100.000 đến 200.000 đồng
🤖 Gemini Thuần: Theo Nghị định 100/2019/NĐ-CP (được sửa đổi, bổ sung bởi Nghị định 123/2021/NĐ-CP), mức phạt đối với
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ với hơn 30 năm kinh nghiệm, tôi xin g
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0286, F1_RAG=0.0113, P@5=0.0
⏱️ Latency     : 6.76s

────────────────────────────────────────────────────────────
[25] ❓ Ô tô không dừng nhường đường cho người đi bộ bị phạt gì?
✅ Ground Truth : Phạt tiền từ 1.000.000 đến 2.000.000 đồng
🤖 Gemini Thuần: Theo quy định tại **Nghị định 100/2019/NĐ-CP** (được sửa đổi bởi Nghị định 123/2021/NĐ-CP), hành vi
🔍 Agentic RAG : Chào bạn, với tư cách là Luật sư chuyên về Giao thông đường bộ, tôi xin giải đáp thắc mắc của bạn về
📊 Metrics     : Cosine_RAG=0.0, ROUGE-L_RAG=0.0511, F1_RAG=0.0312, P@5=1.0
⏱️ Latency     : 5.76s

## 6. Đánh Giá Ragas (Faithfulness & Answer Relevancy)

> Ragas dùng LLM để chấm điểm — cần thêm API key và cài thư viện `ragas`

In [21]:
# ==== RAGAS EVALUATION (dùng Gemini thay vì OpenAI) ====
RAGAS_OK = False
try:
    from datasets import Dataset
    from ragas import evaluate
    from ragas.metrics import Faithfulness, AnswerRelevancy
    from ragas.llms import LangchainLLMWrapper
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

    # Cấu hình LLM cho Ragas dùng Gemini 3.1 Flash Lite
    _eval_llm = ChatGoogleGenerativeAI(
        model='gemini-3.1-flash-lite-preview',
        google_api_key=os.getenv('API_KEY'),
        temperature=0
    )
    ragas_llm = LangchainLLMWrapper(_eval_llm)

    # Cấu hình Embeddings cho Ragas
    _eval_emb = GoogleGenerativeAIEmbeddings(
        model='models/gemini-embedding-001',
        google_api_key=os.getenv('API_KEY')
    )
    ragas_embeddings = LangchainEmbeddingsWrapper(_eval_emb)

    # Chuẩn bị dữ liệu cho Ragas
    ragas_data = []
    for _, row in df_eval.iterrows():
        ctx_str = str(row.get('contexts_rag', ''))
        contexts = ctx_str.split(' | ') if ctx_str else ['']
        ragas_data.append({
            'question': row['question'],
            'answer': str(row['answer_rag']),
            'contexts': contexts,
            'ground_truth': str(row['expected_answer'])
        })

    ragas_dataset = Dataset.from_list(ragas_data)
    print(f'🔍 Đang chạy Ragas trên {len(ragas_data)} câu hỏi...')

    ragas_score = evaluate(
        ragas_dataset,
        metrics=[Faithfulness(), AnswerRelevancy()],
        llm=ragas_llm,
        embeddings=ragas_embeddings
    )

    print('\n📊 KẾT QUẢ RAGAS:')
    print(ragas_score)

    ragas_output_path = RESULTS_PATH.replace('.csv', '_ragas_score.json')
    with open(ragas_output_path, 'w', encoding='utf-8') as f_out:
        json.dump(str(ragas_score), f_out, ensure_ascii=False, indent=2)
    print(f'✅ Đã lưu Ragas scores → {ragas_output_path}')
    RAGAS_OK = True

except Exception as e:
    print(f'⚠️ Bỏ qua Ragas evaluation: {e}')

✅ Ragas đã sẵn sàng!

/tmp/ipykernel_54790/4255705122.py:6: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import Faithfulness, AnswerRelevancy
/tmp/ipykernel_54790/4255705122.py:6: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import Faithfulness, AnswerRelevancy

## 7. Lưu Kết Quả Cuối Cùng

In [ ]:
# ==== Lưu tổng hợp cuối cùng ====
FINAL_PATH = RESULTS_PATH.replace('.csv', '_final_eval.csv')
df_eval.to_csv(FINAL_PATH, index=False)
print(f'✅ Đã lưu kết quả cuối cùng → {FINAL_PATH}')

# In tóm tắt cuối
print('\n🏆 TÓM TẮT CUỐI CÙNG:')
print(f'  Số câu hỏi đánh giá: {len(df_eval)}')
print(f'  Cosine (Gemini Thuần): {df_eval["cosine_pure"].mean():.4f}')
print(f'  Cosine (Agentic RAG) : {df_eval["cosine_rag"].mean():.4f}')
print(f'  ROUGE-L (RAG)        : {df_eval["rouge_l_rag"].mean():.4f}')
print(f'  F1 Token (RAG)       : {df_eval["f1_rag"].mean():.4f}')
print(f'  Precision@5 (RAG)    : {df_eval["precision_at_5"].mean():.4f}')
print(f'  Avg Latency (RAG)    : {df_eval["latency"].mean():.2f}s')